// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/rollout.proto

package rolloutpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RolloutControl_StartRollout_FullMethodName    = "/rollout.v1.RolloutControl/StartRollout"
	RolloutControl_StreamDecisions_FullMethodName = "/rollout.v1.RolloutControl/StreamDecisions"
)

// RolloutControlClient is the client API for RolloutControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RolloutControlClient interface {
	StartRollout(ctx context.Context, in *StartRolloutRequest, opts ...grpc.CallOption) (*StartRolloutResponse, error)
	StreamDecisions(ctx context.Context, in *StreamDecisionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DecisionEvent], error)
}

type rolloutControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRolloutControlClient(cc grpc.ClientConnInterface) RolloutControlClient {
	return &rolloutControlClient{cc}
}

func (c *rolloutControlClient) StartRollout(ctx context.Context, in *StartRolloutRequest, opts ...grpc.CallOption) (*StartRolloutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRolloutResponse)
	err := c.cc.Invoke(ctx, RolloutControl_StartRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutControlClient) StreamDecisions(ctx context.Context, in *StreamDecisionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DecisionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RolloutControl_ServiceDesc.Streams[0], RolloutControl_StreamDecisions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamDecisionsRequest, DecisionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RolloutControl_StreamDecisionsClient = grpc.ServerStreamingClient[DecisionEvent]

// RolloutControlServer is the server API for RolloutControl service.
// All implementations must embed UnimplementedRolloutControlServer
// for forward compatibility.
type RolloutControlServer interface {
	StartRollout(context.Context, *StartRolloutRequest) (*StartRolloutResponse, error)
	StreamDecisions(*StreamDecisionsRequest, grpc.ServerStreamingServer[DecisionEvent]) error
	mustEmbedUnimplementedRolloutControlServer()
}

// UnimplementedRolloutControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRolloutControlServer struct{}

func (UnimplementedRolloutControlServer) StartRollout(context.Context, *StartRolloutRequest) (*StartRolloutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRollout not implemented")
}
func (UnimplementedRolloutControlServer) StreamDecisions(*StreamDecisionsRequest, grpc.ServerStreamingServer[DecisionEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamDecisions not implemented")
}
func (UnimplementedRolloutControlServer) mustEmbedUnimplementedRolloutControlServer() {}
func (UnimplementedRolloutControlServer) testEmbeddedByValue()                        {}

// UnsafeRolloutControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RolloutControlServer will
// result in compilation errors.
type UnsafeRolloutControlServer interface {
	mustEmbedUnimplementedRolloutControlServer()
}

func RegisterRolloutControlServer(s grpc.ServiceRegistrar, srv RolloutControlServer) {
	// If the following call panics, it indicates UnimplementedRolloutControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RolloutControl_ServiceDesc, srv)
}

func _RolloutControl_StartRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutControlServer).StartRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutControl_StartRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutControlServer).StartRollout(ctx, req.(*StartRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutControl_StreamDecisions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamDecisionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RolloutControlServer).StreamDecisions(m, &grpc.GenericServerStream[StreamDecisionsRequest, DecisionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RolloutControl_StreamDecisionsServer = grpc.ServerStreamingServer[DecisionEvent]

// RolloutControl_ServiceDesc is the grpc.ServiceDesc for RolloutControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RolloutControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rollout.v1.RolloutControl",
	HandlerType: (*RolloutControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRollout",
			Handler:    _RolloutControl_StartRollout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDecisions",
			Handler:       _RolloutControl_StreamDecisions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/rollout.proto",
}
