// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/rollout.proto

package rolloutpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecisionType int32

const (
	DecisionType_DECISION_UNKNOWN DecisionType = 0
	DecisionType_PROMOTE          DecisionType = 1
	DecisionType_PAUSE            DecisionType = 2
	DecisionType_ROLLBACK         DecisionType = 3
)

// Enum value maps for DecisionType.
var (
	DecisionType_name = map[int32]string{
		0: "DECISION_UNKNOWN",
		1: "PROMOTE",
		2: "PAUSE",
		3: "ROLLBACK",
	}
	DecisionType_value = map[string]int32{
		"DECISION_UNKNOWN": 0,
		"PROMOTE":          1,
		"PAUSE":            2,
		"ROLLBACK":         3,
	}
)

func (x DecisionType) Enum() *DecisionType {
	p := new(DecisionType)
	*p = x
	return p
}

func (x DecisionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rollout_proto_enumTypes[0].Descriptor()
}

func (DecisionType) Type() protoreflect.EnumType {
	return &file_proto_rollout_proto_enumTypes[0]
}

func (x DecisionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionType.Descriptor instead.
func (DecisionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_rollout_proto_rawDescGZIP(), []int{0}
}

type StartRolloutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRolloutRequest) Reset() {
	*x = StartRolloutRequest{}
	mi := &file_proto_rollout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRolloutRequest) ProtoMessage() {}

func (x *StartRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rollout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRolloutRequest.ProtoReflect.Descriptor instead.
func (*StartRolloutRequest) Descriptor() ([]byte, []int) {
	return file_proto_rollout_proto_rawDescGZIP(), []int{0}
}

func (x *StartRolloutRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *StartRolloutRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StartRolloutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRolloutResponse) Reset() {
	*x = StartRolloutResponse{}
	mi := &file_proto_rollout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRolloutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRolloutResponse) ProtoMessage() {}

func (x *StartRolloutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rollout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRolloutResponse.ProtoReflect.Descriptor instead.
func (*StartRolloutResponse) Descriptor() ([]byte, []int) {
	return file_proto_rollout_proto_rawDescGZIP(), []int{1}
}

func (x *StartRolloutResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type StreamDecisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDecisionsRequest) Reset() {
	*x = StreamDecisionsRequest{}
	mi := &file_proto_rollout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDecisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDecisionsRequest) ProtoMessage() {}

func (x *StreamDecisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rollout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDecisionsRequest.ProtoReflect.Descriptor instead.
func (*StreamDecisionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rollout_proto_rawDescGZIP(), []int{2}
}

func (x *StreamDecisionsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type TelemetryEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	LatencyMs       float64                `protobuf:"fixed64,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Error           bool                   `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_proto_rollout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rollout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_proto_rollout_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *TelemetryEvent) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *TelemetryEvent) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *TelemetryEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type AggregatedMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServiceId         string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	P95LatencyMs      float64                `protobuf:"fixed64,2,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	ErrorRate         float64                `protobuf:"fixed64,3,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	WindowStartUnixMs int64                  `protobuf:"varint,4,opt,name=window_start_unix_ms,json=windowStartUnixMs,proto3" json:"window_start_unix_ms,omitempty"`
	WindowEndUnixMs   int64                  `protobuf:"varint,5,opt,name=window_end_unix_ms,json=windowEndUnixMs,proto3" json:"window_end_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AggregatedMetrics) Reset() {
	*x = AggregatedMetrics{}
	mi := &file_proto_rollout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedMetrics) ProtoMessage() {}

func (x *AggregatedMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rollout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedMetrics.ProtoReflect.Descriptor instead.
func (*AggregatedMetrics) Descriptor() ([]byte, []int) {
	return file_proto_rollout_proto_rawDescGZIP(), []int{4}
}

func (x *AggregatedMetrics) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *AggregatedMetrics) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *AggregatedMetrics) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *AggregatedMetrics) GetWindowStartUnixMs() int64 {
	if x != nil {
		return x.WindowStartUnixMs
	}
	return 0
}

func (x *AggregatedMetrics) GetWindowEndUnixMs() int64 {
	if x != nil {
		return x.WindowEndUnixMs
	}
	return 0
}

type DecisionEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Decision        DecisionType           `protobuf:"varint,2,opt,name=decision,proto3,enum=rollout.v1.DecisionType" json:"decision,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DecisionEvent) Reset() {
	*x = DecisionEvent{}
	mi := &file_proto_rollout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionEvent) ProtoMessage() {}

func (x *DecisionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rollout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionEvent.ProtoReflect.Descriptor instead.
func (*DecisionEvent) Descriptor() ([]byte, []int) {
	return file_proto_rollout_proto_rawDescGZIP(), []int{5}
}

func (x *DecisionEvent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DecisionEvent) GetDecision() DecisionType {
	if x != nil {
		return x.Decision
	}
	return DecisionType_DECISION_UNKNOWN
}

func (x *DecisionEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DecisionEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

var File_proto_rollout_proto protoreflect.FileDescriptor

const file_proto_rollout_proto_rawDesc = "" +
	"\n" +
	"\x13proto/rollout.proto\x12\n" +
	"rollout.v1\"N\n" +
	"\x13StartRolloutRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"2\n" +
	"\x14StartRolloutResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"7\n" +
	"\x16StreamDecisionsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"\x90\x01\n" +
	"\x0eTelemetryEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x01R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\bR\x05error\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs\"\xd5\x01\n" +
	"\x11AggregatedMetrics\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12$\n" +
	"\x0ep95_latency_ms\x18\x02 \x01(\x01R\fp95LatencyMs\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x03 \x01(\x01R\terrorRate\x12/\n" +
	"\x14window_start_unix_ms\x18\x04 \x01(\x03R\x11windowStartUnixMs\x12+\n" +
	"\x12window_end_unix_ms\x18\x05 \x01(\x03R\x0fwindowEndUnixMs\"\xa8\x01\n" +
	"\rDecisionEvent\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x124\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x18.rollout.v1.DecisionTypeR\bdecision\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs*J\n" +
	"\fDecisionType\x12\x14\n" +
	"\x10DECISION_UNKNOWN\x10\x00\x12\v\n" +
	"\aPROMOTE\x10\x01\x12\t\n" +
	"\x05PAUSE\x10\x02\x12\f\n" +
	"\bROLLBACK\x10\x032\xb7\x01\n" +
	"\x0eRolloutControl\x12Q\n" +
	"\fStartRollout\x12\x1f.rollout.v1.StartRolloutRequest\x1a .rollout.v1.StartRolloutResponse\x12R\n" +
	"\x0fStreamDecisions\x12\".rollout.v1.StreamDecisionsRequest\x1a\x19.rollout.v1.DecisionEvent0\x01BNZLgithub.com/vineet4007/real-time-canary-control-plane/internal/grpc/rolloutpbb\x06proto3"

var (
	file_proto_rollout_proto_rawDescOnce sync.Once
	file_proto_rollout_proto_rawDescData []byte
)

func file_proto_rollout_proto_rawDescGZIP() []byte {
	file_proto_rollout_proto_rawDescOnce.Do(func() {
		file_proto_rollout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rollout_proto_rawDesc), len(file_proto_rollout_proto_rawDesc)))
	})
	return file_proto_rollout_proto_rawDescData
}

var file_proto_rollout_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_rollout_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_rollout_proto_goTypes = []any{
	(DecisionType)(0),              // 0: rollout.v1.DecisionType
	(*StartRolloutRequest)(nil),    // 1: rollout.v1.StartRolloutRequest
	(*StartRolloutResponse)(nil),   // 2: rollout.v1.StartRolloutResponse
	(*StreamDecisionsRequest)(nil), // 3: rollout.v1.StreamDecisionsRequest
	(*TelemetryEvent)(nil),         // 4: rollout.v1.TelemetryEvent
	(*AggregatedMetrics)(nil),      // 5: rollout.v1.AggregatedMetrics
	(*DecisionEvent)(nil),          // 6: rollout.v1.DecisionEvent
}
var file_proto_rollout_proto_depIdxs = []int32{
	0, // 0: rollout.v1.DecisionEvent.decision:type_name -> rollout.v1.DecisionType
	1, // 1: rollout.v1.RolloutControl.StartRollout:input_type -> rollout.v1.StartRolloutRequest
	3, // 2: rollout.v1.RolloutControl.StreamDecisions:input_type -> rollout.v1.StreamDecisionsRequest
	2, // 3: rollout.v1.RolloutControl.StartRollout:output_type -> rollout.v1.StartRolloutResponse
	6, // 4: rollout.v1.RolloutControl.StreamDecisions:output_type -> rollout.v1.DecisionEvent
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_rollout_proto_init() }
func file_proto_rollout_proto_init() {
	if File_proto_rollout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rollout_proto_rawDesc), len(file_proto_rollout_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rollout_proto_goTypes,
		DependencyIndexes: file_proto_rollout_proto_depIdxs,
		EnumInfos:         file_proto_rollout_proto_enumTypes,
		MessageInfos:      file_proto_rollout_proto_msgTypes,
	}.Build()
	File_proto_rollout_proto = out.File
	file_proto_rollout_proto_goTypes = nil
	file_proto_rollout_proto_depIdxs = nil
}
